// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAppointmentEvent = `-- name: InsertAppointmentEvent :exec
INSERT INTO appointment_events (
    appointment_id, kind, from_status, to_status, previous_range, new_range, actor,
    actor_user_id, detail
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
`

type InsertAppointmentEventParams struct {
	AppointmentID pgtype.UUID
	Kind          string
	FromStatus    pgtype.Text
	ToStatus      pgtype.Text
	PreviousRange pgtype.Range[pgtype.Timestamptz]
	NewRange      pgtype.Range[pgtype.Timestamptz]
	Actor         string
	ActorUserID   pgtype.UUID
	Detail        []byte
}

func (q *Queries) InsertAppointmentEvent(ctx context.Context, arg InsertAppointmentEventParams) error {
	_, err := q.db.Exec(ctx, insertAppointmentEvent,
		arg.AppointmentID,
		arg.Kind,
		arg.FromStatus,
		arg.ToStatus,
		arg.PreviousRange,
		arg.NewRange,
		arg.Actor,
		arg.ActorUserID,
		arg.Detail,
	)
	return err
}
