// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_events.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAppointmentEvent = `-- name: InsertAppointmentEvent :exec
INSERT INTO appointment_events (
    appointment_id, kind, from_status, to_status, previous_range, new_range, actor,
    actor_user_id, detail
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
`

type InsertAppointmentEventParams struct {
	AppointmentID pgtype.UUID
	Kind          string
	FromStatus    pgtype.Text
	ToStatus      pgtype.Text
	PreviousRange pgtype.Range[pgtype.Timestamptz]
	NewRange      pgtype.Range[pgtype.Timestamptz]
	Actor         string
	ActorUserID   pgtype.UUID
	Detail        []byte
}

func (q *Queries) InsertAppointmentEvent(ctx context.Context, arg InsertAppointmentEventParams) error {
	_, err := q.db.Exec(ctx, insertAppointmentEvent,
		arg.AppointmentID,
		arg.Kind,
		arg.FromStatus,
		arg.ToStatus,
		arg.PreviousRange,
		arg.NewRange,
		arg.Actor,
		arg.ActorUserID,
		arg.Detail,
	)
	return err
}

const latestRescheduleRequest = `-- name: LatestRescheduleRequest :one
SELECT detail FROM appointment_events
WHERE appointment_id = $1 AND kind = 'reschedule_requested'
ORDER BY id DESC
LIMIT 1
`

// LatestRescheduleRequest is the detail of the visitor's newest request.
func (q *Queries) LatestRescheduleRequest(ctx context.Context, appointmentID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestRescheduleRequest, appointmentID)
	var detail []byte
	err := row.Scan(&detail)
	return detail, err
}

const listAppointmentEvents = `-- name: ListAppointmentEvents :many
SELECT e.id, e.appointment_id, e.kind, e.from_status, e.to_status, e.previous_range, e.new_range, e.actor, e.actor_user_id, e.detail, e.created_at, u.display_name AS actor_name
FROM appointment_events e
LEFT JOIN users u ON u.id = e.actor_user_id
WHERE e.appointment_id = $1
ORDER BY e.created_at, e.id
`

type ListAppointmentEventsRow struct {
	ID            int64
	AppointmentID pgtype.UUID
	Kind          string
	FromStatus    pgtype.Text
	ToStatus      pgtype.Text
	PreviousRange pgtype.Range[pgtype.Timestamptz]
	NewRange      pgtype.Range[pgtype.Timestamptz]
	Actor         string
	ActorUserID   pgtype.UUID
	Detail        []byte
	CreatedAt     time.Time
	ActorName     pgtype.Text
}

func (q *Queries) ListAppointmentEvents(ctx context.Context, appointmentID pgtype.UUID) ([]ListAppointmentEventsRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentEvents, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentEventsRow{}
	for rows.Next() {
		var i ListAppointmentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.Kind,
			&i.FromStatus,
			&i.ToStatus,
			&i.PreviousRange,
			&i.NewRange,
			&i.Actor,
			&i.ActorUserID,
			&i.Detail,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleRequestOpen = `-- name: RescheduleRequestOpen :one
SELECT EXISTS (
    SELECT 1 FROM appointment_events r
    WHERE r.appointment_id = $1 AND r.kind = 'reschedule_requested'
      AND r.id > coalesce((
          SELECT max(e.id) FROM appointment_events e
          WHERE e.appointment_id = $1 AND (e.kind = 'rescheduled' OR e.to_status IS NOT NULL)
      ), 0)
)::bool
`

// RescheduleRequestOpen reports a reschedule request newer than the last
// reschedule or status change, which would have answered it.
func (q *Queries) RescheduleRequestOpen(ctx context.Context, appointmentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, rescheduleRequestOpen, appointmentID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
