// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAppointment = `-- name: InsertAppointment :one
INSERT INTO appointments (
    reference, practitioner_id, service_id, status, starts_at, ends_at, duration_minutes,
    busy_range, timezone, format, locale, source, visitor_name, visitor_email, visitor_phone,
    visitor_note, privacy_ack_at, policy_ack_at, hold_expires_at, management_token_seed,
    management_token_hash, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21, $22
)
ON CONFLICT (reference) DO NOTHING
RETURNING id, reference, practitioner_id, service_id, status, starts_at, ends_at, duration_minutes, busy_range, timezone, format, locale, source, visitor_name, visitor_email, visitor_phone, visitor_note, privacy_ack_at, policy_ack_at, hold_expires_at, management_token_seed, management_token_hash, meeting_link, admin_note, late_cancellation, status_changed_at, created_by, version, created_at, updated_at
`

type InsertAppointmentParams struct {
	Reference           string
	PractitionerID      pgtype.UUID
	ServiceID           pgtype.UUID
	Status              string
	StartsAt            time.Time
	EndsAt              time.Time
	DurationMinutes     int32
	BusyRange           pgtype.Range[pgtype.Timestamptz]
	Timezone            string
	Format              string
	Locale              string
	Source              string
	VisitorName         string
	VisitorEmail        string
	VisitorPhone        pgtype.Text
	VisitorNote         pgtype.Text
	PrivacyAckAt        sql.NullTime
	PolicyAckAt         sql.NullTime
	HoldExpiresAt       sql.NullTime
	ManagementTokenSeed []byte
	ManagementTokenHash []byte
	CreatedBy           pgtype.UUID
}

// InsertAppointment does nothing on a reference collision, so the caller can
// retry with a new reference inside the same transaction. Every other
// violation, appointments_no_overlap included, is an error.
func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, insertAppointment,
		arg.Reference,
		arg.PractitionerID,
		arg.ServiceID,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.DurationMinutes,
		arg.BusyRange,
		arg.Timezone,
		arg.Format,
		arg.Locale,
		arg.Source,
		arg.VisitorName,
		arg.VisitorEmail,
		arg.VisitorPhone,
		arg.VisitorNote,
		arg.PrivacyAckAt,
		arg.PolicyAckAt,
		arg.HoldExpiresAt,
		arg.ManagementTokenSeed,
		arg.ManagementTokenHash,
		arg.CreatedBy,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PractitionerID,
		&i.ServiceID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.DurationMinutes,
		&i.BusyRange,
		&i.Timezone,
		&i.Format,
		&i.Locale,
		&i.Source,
		&i.VisitorName,
		&i.VisitorEmail,
		&i.VisitorPhone,
		&i.VisitorNote,
		&i.PrivacyAckAt,
		&i.PolicyAckAt,
		&i.HoldExpiresAt,
		&i.ManagementTokenSeed,
		&i.ManagementTokenHash,
		&i.MeetingLink,
		&i.AdminNote,
		&i.LateCancellation,
		&i.StatusChangedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverdueHolds = `-- name: ListOverdueHolds :many
SELECT id FROM appointments
WHERE status = 'pending' AND hold_expires_at <= $1::timestamptz
ORDER BY hold_expires_at
LIMIT $2
`

type ListOverdueHoldsParams struct {
	Now     time.Time
	MaxRows int32
}

// ListOverdueHolds serves booking:sweep-holds through the partial index on
// pending holds.
func (q *Queries) ListOverdueHolds(ctx context.Context, arg ListOverdueHoldsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOverdueHolds, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverlappingAppointments = `-- name: ListOverlappingAppointments :many
SELECT a.id, a.reference, a.status, a.starts_at, a.ends_at, a.duration_minutes, a.timezone,
       a.format, a.source, a.visitor_name, a.hold_expires_at, a.created_at, a.updated_at,
       s.id AS service_id, s.slug AS service_slug, s.name AS service_name
FROM appointments a
JOIN services s ON s.id = a.service_id
WHERE a.status IN ('pending', 'confirmed') AND a.busy_range && $1::tstzrange
ORDER BY a.starts_at
`

type ListOverlappingAppointmentsRow struct {
	ID              pgtype.UUID
	Reference       string
	Status          string
	StartsAt        time.Time
	EndsAt          time.Time
	DurationMinutes int32
	Timezone        string
	Format          string
	Source          string
	VisitorName     string
	HoldExpiresAt   sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ServiceID       pgtype.UUID
	ServiceSlug     string
	ServiceName     json.RawMessage
}

func (q *Queries) ListOverlappingAppointments(ctx context.Context, period pgtype.Range[pgtype.Timestamptz]) ([]ListOverlappingAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listOverlappingAppointments, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverlappingAppointmentsRow{}
	for rows.Next() {
		var i ListOverlappingAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.DurationMinutes,
			&i.Timezone,
			&i.Format,
			&i.Source,
			&i.VisitorName,
			&i.HoldExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceID,
			&i.ServiceSlug,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppointment = `-- name: LockAppointment :one
SELECT id, reference, practitioner_id, service_id, status, starts_at, ends_at, duration_minutes, busy_range, timezone, format, locale, source, visitor_name, visitor_email, visitor_phone, visitor_note, privacy_ack_at, policy_ack_at, hold_expires_at, management_token_seed, management_token_hash, meeting_link, admin_note, late_cancellation, status_changed_at, created_by, version, created_at, updated_at FROM appointments WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, lockAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PractitionerID,
		&i.ServiceID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.DurationMinutes,
		&i.BusyRange,
		&i.Timezone,
		&i.Format,
		&i.Locale,
		&i.Source,
		&i.VisitorName,
		&i.VisitorEmail,
		&i.VisitorPhone,
		&i.VisitorNote,
		&i.PrivacyAckAt,
		&i.PolicyAckAt,
		&i.HoldExpiresAt,
		&i.ManagementTokenSeed,
		&i.ManagementTokenHash,
		&i.MeetingLink,
		&i.AdminNote,
		&i.LateCancellation,
		&i.StatusChangedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSchedule = `-- name: LockSchedule :exec
SELECT pg_advisory_xact_lock(hashtext(
    'availability:' || coalesce((SELECT id::text FROM users WHERE is_practitioner), '')))
`

// LockSchedule takes the transaction-scoped lock that availability writes and
// appointment creation share (docs/architecture.md, walkthrough 1, step 5),
// keyed by the one practitioner.
func (q *Queries) LockSchedule(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSchedule)
	return err
}

const setAppointmentStatus = `-- name: SetAppointmentStatus :one
UPDATE appointments
SET status = $1, status_changed_at = $2, updated_at = $2, version = version + 1
WHERE id = $3
RETURNING id, reference, practitioner_id, service_id, status, starts_at, ends_at, duration_minutes, busy_range, timezone, format, locale, source, visitor_name, visitor_email, visitor_phone, visitor_note, privacy_ack_at, policy_ack_at, hold_expires_at, management_token_seed, management_token_hash, meeting_link, admin_note, late_cancellation, status_changed_at, created_by, version, created_at, updated_at
`

type SetAppointmentStatusParams struct {
	Status string
	Now    time.Time
	ID     pgtype.UUID
}

// SetAppointmentStatus is the one write of a status change; the caller has
// checked it with booking.CanTransition.
func (q *Queries) SetAppointmentStatus(ctx context.Context, arg SetAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, setAppointmentStatus, arg.Status, arg.Now, arg.ID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PractitionerID,
		&i.ServiceID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.DurationMinutes,
		&i.BusyRange,
		&i.Timezone,
		&i.Format,
		&i.Locale,
		&i.Source,
		&i.VisitorName,
		&i.VisitorEmail,
		&i.VisitorPhone,
		&i.VisitorNote,
		&i.PrivacyAckAt,
		&i.PolicyAckAt,
		&i.HoldExpiresAt,
		&i.ManagementTokenSeed,
		&i.ManagementTokenHash,
		&i.MeetingLink,
		&i.AdminNote,
		&i.LateCancellation,
		&i.StatusChangedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
