// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability_rules.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailabilityRule = `-- name: CreateAvailabilityRule :one
INSERT INTO availability_rules (weekday, start_time, end_time)
VALUES ($1, $2, $3)
RETURNING id, weekday, start_time, end_time, created_at, updated_at
`

type CreateAvailabilityRuleParams struct {
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

func (q *Queries) CreateAvailabilityRule(ctx context.Context, arg CreateAvailabilityRuleParams) (AvailabilityRule, error) {
	row := q.db.QueryRow(ctx, createAvailabilityRule, arg.Weekday, arg.StartTime, arg.EndTime)
	var i AvailabilityRule
	err := row.Scan(
		&i.ID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailabilityRule = `-- name: DeleteAvailabilityRule :execrows
DELETE FROM availability_rules WHERE id = $1
`

func (q *Queries) DeleteAvailabilityRule(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailabilityRules = `-- name: ListAvailabilityRules :many
SELECT id, weekday, start_time, end_time, created_at, updated_at FROM availability_rules ORDER BY weekday, start_time
`

func (q *Queries) ListAvailabilityRules(ctx context.Context) ([]AvailabilityRule, error) {
	rows, err := q.db.Query(ctx, listAvailabilityRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityRule{}
	for rows.Next() {
		var i AvailabilityRule
		if err := rows.Scan(
			&i.ID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailabilityRule = `-- name: UpdateAvailabilityRule :one
UPDATE availability_rules
SET weekday = $1, start_time = $2, end_time = $3, updated_at = $4
WHERE id = $5
RETURNING id, weekday, start_time, end_time, created_at, updated_at
`

type UpdateAvailabilityRuleParams struct {
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Now       time.Time
	ID        pgtype.UUID
}

func (q *Queries) UpdateAvailabilityRule(ctx context.Context, arg UpdateAvailabilityRuleParams) (AvailabilityRule, error) {
	row := q.db.QueryRow(ctx, updateAvailabilityRule,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.Now,
		arg.ID,
	)
	var i AvailabilityRule
	err := row.Scan(
		&i.ID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
