// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability_blocks.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailabilityBlock = `-- name: CreateAvailabilityBlock :one
INSERT INTO availability_blocks (period, all_day, reason, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, period, all_day, reason, created_by, created_at, updated_at
`

type CreateAvailabilityBlockParams struct {
	Period    pgtype.Range[pgtype.Timestamptz]
	AllDay    bool
	Reason    pgtype.Text
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateAvailabilityBlock(ctx context.Context, arg CreateAvailabilityBlockParams) (AvailabilityBlock, error) {
	row := q.db.QueryRow(ctx, createAvailabilityBlock,
		arg.Period,
		arg.AllDay,
		arg.Reason,
		arg.CreatedBy,
	)
	var i AvailabilityBlock
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.AllDay,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailabilityBlock = `-- name: DeleteAvailabilityBlock :execrows
DELETE FROM availability_blocks WHERE id = $1
`

func (q *Queries) DeleteAvailabilityBlock(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityBlock, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailabilityBlocks = `-- name: ListAvailabilityBlocks :many
SELECT id, period, all_day, reason, created_by, created_at, updated_at FROM availability_blocks
WHERE period && $1::tstzrange
ORDER BY lower(period)
`

func (q *Queries) ListAvailabilityBlocks(ctx context.Context, within pgtype.Range[pgtype.Timestamptz]) ([]AvailabilityBlock, error) {
	rows, err := q.db.Query(ctx, listAvailabilityBlocks, within)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityBlock{}
	for rows.Next() {
		var i AvailabilityBlock
		if err := rows.Scan(
			&i.ID,
			&i.Period,
			&i.AllDay,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailabilityBlock = `-- name: UpdateAvailabilityBlock :one
UPDATE availability_blocks
SET period = $1, all_day = $2, reason = $3, updated_at = $4
WHERE id = $5
RETURNING id, period, all_day, reason, created_by, created_at, updated_at
`

type UpdateAvailabilityBlockParams struct {
	Period pgtype.Range[pgtype.Timestamptz]
	AllDay bool
	Reason pgtype.Text
	Now    time.Time
	ID     pgtype.UUID
}

func (q *Queries) UpdateAvailabilityBlock(ctx context.Context, arg UpdateAvailabilityBlockParams) (AvailabilityBlock, error) {
	row := q.db.QueryRow(ctx, updateAvailabilityBlock,
		arg.Period,
		arg.AllDay,
		arg.Reason,
		arg.Now,
		arg.ID,
	)
	var i AvailabilityBlock
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.AllDay,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
