// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability_overrides.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailabilityOverride = `-- name: CreateAvailabilityOverride :one
INSERT INTO availability_overrides (on_date, kind, period, note, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, on_date, kind, period, note, created_by, created_at, updated_at
`

type CreateAvailabilityOverrideParams struct {
	OnDate    pgtype.Date
	Kind      string
	Period    pgtype.Range[pgtype.Timestamptz]
	Note      pgtype.Text
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateAvailabilityOverride(ctx context.Context, arg CreateAvailabilityOverrideParams) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, createAvailabilityOverride,
		arg.OnDate,
		arg.Kind,
		arg.Period,
		arg.Note,
		arg.CreatedBy,
	)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.OnDate,
		&i.Kind,
		&i.Period,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailabilityOverride = `-- name: DeleteAvailabilityOverride :execrows
DELETE FROM availability_overrides WHERE id = $1
`

func (q *Queries) DeleteAvailabilityOverride(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityOverride, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailabilityOverrides = `-- name: ListAvailabilityOverrides :many
SELECT id, on_date, kind, period, note, created_by, created_at, updated_at FROM availability_overrides
WHERE on_date BETWEEN $1 AND $2
ORDER BY on_date, lower(period)
`

type ListAvailabilityOverridesParams struct {
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

func (q *Queries) ListAvailabilityOverrides(ctx context.Context, arg ListAvailabilityOverridesParams) ([]AvailabilityOverride, error) {
	rows, err := q.db.Query(ctx, listAvailabilityOverrides, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityOverride{}
	for rows.Next() {
		var i AvailabilityOverride
		if err := rows.Scan(
			&i.ID,
			&i.OnDate,
			&i.Kind,
			&i.Period,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailabilityOverride = `-- name: UpdateAvailabilityOverride :one
UPDATE availability_overrides
SET on_date = $1, kind = $2, period = $3, note = $4, updated_at = $5
WHERE id = $6
RETURNING id, on_date, kind, period, note, created_by, created_at, updated_at
`

type UpdateAvailabilityOverrideParams struct {
	OnDate pgtype.Date
	Kind   string
	Period pgtype.Range[pgtype.Timestamptz]
	Note   pgtype.Text
	Now    time.Time
	ID     pgtype.UUID
}

func (q *Queries) UpdateAvailabilityOverride(ctx context.Context, arg UpdateAvailabilityOverrideParams) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, updateAvailabilityOverride,
		arg.OnDate,
		arg.Kind,
		arg.Period,
		arg.Note,
		arg.Now,
		arg.ID,
	)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.OnDate,
		&i.Kind,
		&i.Period,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
