// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability_busy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBusyPeriods = `-- name: ListBusyPeriods :many
SELECT busy_range AS period FROM appointments
WHERE status IN ('pending', 'confirmed') AND busy_range && $1::tstzrange
  AND ($2::uuid IS NULL OR id <> $2::uuid)
UNION ALL
SELECT period FROM availability_blocks
WHERE period && $1::tstzrange
`

type ListBusyPeriodsParams struct {
	Within   pgtype.Range[pgtype.Timestamptz]
	ExceptID pgtype.UUID
}

// ListBusyPeriods is the time slot generation must keep free inside within:
// every block and every pending or confirmed appointment's busy range. It
// selects the periods alone, never a reason or anything about a visitor.
// @except_id, when set, is an appointment being moved, whose own time is free
// to it.
func (q *Queries) ListBusyPeriods(ctx context.Context, arg ListBusyPeriodsParams) ([]pgtype.Range[pgtype.Timestamptz], error) {
	rows, err := q.db.Query(ctx, listBusyPeriods, arg.Within, arg.ExceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Range[pgtype.Timestamptz]{}
	for rows.Next() {
		var period pgtype.Range[pgtype.Timestamptz]
		if err := rows.Scan(&period); err != nil {
			return nil, err
		}
		items = append(items, period)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
