// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communications.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppointmentForMessage = `-- name: GetAppointmentForMessage :one
SELECT a.id, a.reference, a.practitioner_id, a.service_id, a.status, a.starts_at, a.ends_at, a.duration_minutes, a.busy_range, a.timezone, a.format, a.locale, a.source, a.visitor_name, a.visitor_email, a.visitor_phone, a.visitor_note, a.privacy_ack_at, a.policy_ack_at, a.hold_expires_at, a.management_token_seed, a.management_token_hash, a.meeting_link, a.admin_note, a.late_cancellation, a.status_changed_at, a.created_by, a.version, a.created_at, a.updated_at, s.name AS service_name, s.fee_text AS service_fee_text,
       s.preparation_text AS service_preparation_text
FROM appointments a
JOIN services s ON s.id = a.service_id
WHERE a.id = $1
`

type GetAppointmentForMessageRow struct {
	ID                     pgtype.UUID
	Reference              string
	PractitionerID         pgtype.UUID
	ServiceID              pgtype.UUID
	Status                 string
	StartsAt               time.Time
	EndsAt                 time.Time
	DurationMinutes        int32
	BusyRange              pgtype.Range[pgtype.Timestamptz]
	Timezone               string
	Format                 string
	Locale                 string
	Source                 string
	VisitorName            string
	VisitorEmail           string
	VisitorPhone           pgtype.Text
	VisitorNote            pgtype.Text
	PrivacyAckAt           sql.NullTime
	PolicyAckAt            sql.NullTime
	HoldExpiresAt          sql.NullTime
	ManagementTokenSeed    []byte
	ManagementTokenHash    []byte
	MeetingLink            pgtype.Text
	AdminNote              pgtype.Text
	LateCancellation       bool
	StatusChangedAt        time.Time
	CreatedBy              pgtype.UUID
	Version                int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ServiceName            json.RawMessage
	ServiceFeeText         json.RawMessage
	ServicePreparationText json.RawMessage
}

func (q *Queries) GetAppointmentForMessage(ctx context.Context, id pgtype.UUID) (GetAppointmentForMessageRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentForMessage, id)
	var i GetAppointmentForMessageRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PractitionerID,
		&i.ServiceID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.DurationMinutes,
		&i.BusyRange,
		&i.Timezone,
		&i.Format,
		&i.Locale,
		&i.Source,
		&i.VisitorName,
		&i.VisitorEmail,
		&i.VisitorPhone,
		&i.VisitorNote,
		&i.PrivacyAckAt,
		&i.PolicyAckAt,
		&i.HoldExpiresAt,
		&i.ManagementTokenSeed,
		&i.ManagementTokenHash,
		&i.MeetingLink,
		&i.AdminNote,
		&i.LateCancellation,
		&i.StatusChangedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceName,
		&i.ServiceFeeText,
		&i.ServicePreparationText,
	)
	return i, err
}

const getCommunication = `-- name: GetCommunication :one
SELECT id, appointment_id, contact_enquiry_id, kind, audience, channel, recipient, locale, status, scheduled_for, sent_at, provider_message_id, error, attempts, resend_of, created_by, note, created_at, message FROM communications WHERE id = $1
`

func (q *Queries) GetCommunication(ctx context.Context, id pgtype.UUID) (Communication, error) {
	row := q.db.QueryRow(ctx, getCommunication, id)
	var i Communication
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.ContactEnquiryID,
		&i.Kind,
		&i.Audience,
		&i.Channel,
		&i.Recipient,
		&i.Locale,
		&i.Status,
		&i.ScheduledFor,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.Error,
		&i.Attempts,
		&i.ResendOf,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.Message,
	)
	return i, err
}

const insertCommunication = `-- name: InsertCommunication :one
INSERT INTO communications (
    appointment_id, contact_enquiry_id, kind, audience, recipient, locale, scheduled_for, message
) VALUES (
    $1, $2, $3, $4, $5, $6,
    coalesce($7::timestamptz, now()), $8
)
RETURNING id, appointment_id, contact_enquiry_id, kind, audience, channel, recipient, locale, status, scheduled_for, sent_at, provider_message_id, error, attempts, resend_of, created_by, note, created_at, message
`

type InsertCommunicationParams struct {
	AppointmentID    pgtype.UUID
	ContactEnquiryID pgtype.UUID
	Kind             string
	Audience         string
	Recipient        pgtype.Text
	Locale           string
	ScheduledFor     sql.NullTime
	Message          pgtype.Text
}

func (q *Queries) InsertCommunication(ctx context.Context, arg InsertCommunicationParams) (Communication, error) {
	row := q.db.QueryRow(ctx, insertCommunication,
		arg.AppointmentID,
		arg.ContactEnquiryID,
		arg.Kind,
		arg.Audience,
		arg.Recipient,
		arg.Locale,
		arg.ScheduledFor,
		arg.Message,
	)
	var i Communication
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.ContactEnquiryID,
		&i.Kind,
		&i.Audience,
		&i.Channel,
		&i.Recipient,
		&i.Locale,
		&i.Status,
		&i.ScheduledFor,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.Error,
		&i.Attempts,
		&i.ResendOf,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.Message,
	)
	return i, err
}

const listAppointmentCommunications = `-- name: ListAppointmentCommunications :many
SELECT id, appointment_id, contact_enquiry_id, kind, audience, channel, recipient, locale, status, scheduled_for, sent_at, provider_message_id, error, attempts, resend_of, created_by, note, created_at, message FROM communications
WHERE appointment_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAppointmentCommunications(ctx context.Context, appointmentID pgtype.UUID) ([]Communication, error) {
	rows, err := q.db.Query(ctx, listAppointmentCommunications, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Communication{}
	for rows.Next() {
		var i Communication
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.ContactEnquiryID,
			&i.Kind,
			&i.Audience,
			&i.Channel,
			&i.Recipient,
			&i.Locale,
			&i.Status,
			&i.ScheduledFor,
			&i.SentAt,
			&i.ProviderMessageID,
			&i.Error,
			&i.Attempts,
			&i.ResendOf,
			&i.CreatedBy,
			&i.Note,
			&i.CreatedAt,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCommunications = `-- name: ListDueCommunications :many
SELECT id, kind, scheduled_for FROM communications
WHERE status = 'queued' AND scheduled_for < $1
ORDER BY scheduled_for
LIMIT $2
`

type ListDueCommunicationsParams struct {
	Before  time.Time
	MaxRows int32
}

type ListDueCommunicationsRow struct {
	ID           pgtype.UUID
	Kind         string
	ScheduledFor time.Time
}

// ListDueCommunications serves comms:sweep through the partial index on
// queued rows.
func (q *Queries) ListDueCommunications(ctx context.Context, arg ListDueCommunicationsParams) ([]ListDueCommunicationsRow, error) {
	rows, err := q.db.Query(ctx, listDueCommunications, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueCommunicationsRow{}
	for rows.Next() {
		var i ListDueCommunicationsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.ScheduledFor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedReminderIDs = `-- name: ListQueuedReminderIDs :many
SELECT id FROM communications
WHERE appointment_id = $1 AND kind = 'reminder' AND status = 'queued'
`

func (q *Queries) ListQueuedReminderIDs(ctx context.Context, appointmentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listQueuedReminderIDs, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCommunication = `-- name: LockCommunication :one
SELECT id, appointment_id, contact_enquiry_id, kind, audience, channel, recipient, locale, status, scheduled_for, sent_at, provider_message_id, error, attempts, resend_of, created_by, note, created_at, message FROM communications WHERE id = $1 FOR UPDATE SKIP LOCKED
`

// LockCommunication skips a row another worker holds, so two workers given
// the same task never both send it.
func (q *Queries) LockCommunication(ctx context.Context, id pgtype.UUID) (Communication, error) {
	row := q.db.QueryRow(ctx, lockCommunication, id)
	var i Communication
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.ContactEnquiryID,
		&i.Kind,
		&i.Audience,
		&i.Channel,
		&i.Recipient,
		&i.Locale,
		&i.Status,
		&i.ScheduledFor,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.Error,
		&i.Attempts,
		&i.ResendOf,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.Message,
	)
	return i, err
}

const previousRangeOf = `-- name: PreviousRangeOf :one
SELECT previous_range FROM appointment_events
WHERE appointment_id = $1 AND kind = 'rescheduled' AND previous_range IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// PreviousRangeOf is where the latest reschedule moved the appointment from.
func (q *Queries) PreviousRangeOf(ctx context.Context, appointmentID pgtype.UUID) (pgtype.Range[pgtype.Timestamptz], error) {
	row := q.db.QueryRow(ctx, previousRangeOf, appointmentID)
	var previous_range pgtype.Range[pgtype.Timestamptz]
	err := row.Scan(&previous_range)
	return previous_range, err
}

const rescheduleQueuedReminders = `-- name: RescheduleQueuedReminders :many
UPDATE communications c
SET scheduled_for = a.starts_at - make_interval(hours => $1::int)
FROM appointments a
WHERE c.appointment_id = a.id AND c.kind = 'reminder' AND c.status = 'queued'
RETURNING c.id, c.scheduled_for
`

type RescheduleQueuedRemindersRow struct {
	ID           pgtype.UUID
	ScheduledFor time.Time
}

// RescheduleQueuedReminders moves every queued reminder to its start less
// @hours, the new reminder_hours.
func (q *Queries) RescheduleQueuedReminders(ctx context.Context, hours int32) ([]RescheduleQueuedRemindersRow, error) {
	rows, err := q.db.Query(ctx, rescheduleQueuedReminders, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RescheduleQueuedRemindersRow{}
	for rows.Next() {
		var i RescheduleQueuedRemindersRow
		if err := rows.Scan(&i.ID, &i.ScheduledFor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommunicationStatus = `-- name: SetCommunicationStatus :execrows
UPDATE communications
SET status = $1, error = $2, attempts = $3, sent_at = $4,
    provider_message_id = $5
WHERE id = $6 AND status = 'queued'
`

type SetCommunicationStatusParams struct {
	Status            string
	Error             pgtype.Text
	Attempts          int32
	SentAt            sql.NullTime
	ProviderMessageID pgtype.Text
	ID                pgtype.UUID
}

func (q *Queries) SetCommunicationStatus(ctx context.Context, arg SetCommunicationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCommunicationStatus,
		arg.Status,
		arg.Error,
		arg.Attempts,
		arg.SentAt,
		arg.ProviderMessageID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
