// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE platform = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, platform string) error {
	_, err := q.db.Exec(ctx, deleteConnection, platform)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT platform, status, token, account_id, account_name, instagram_id, instagram_username, expires_at, last_error, connected_by, connected_at, updated_at FROM connections WHERE platform = $1
`

func (q *Queries) GetConnection(ctx context.Context, platform string) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, platform)
	var i Connection
	err := row.Scan(
		&i.Platform,
		&i.Status,
		&i.Token,
		&i.AccountID,
		&i.AccountName,
		&i.InstagramID,
		&i.InstagramUsername,
		&i.ExpiresAt,
		&i.LastError,
		&i.ConnectedBy,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveConnection = `-- name: SaveConnection :one
INSERT INTO connections (platform, status, token, account_id, account_name, instagram_id,
                         instagram_username, expires_at, last_error, connected_by, connected_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, NULL, $9, $10, $10)
ON CONFLICT (platform) DO UPDATE
SET status = excluded.status, token = excluded.token, account_id = excluded.account_id,
    account_name = excluded.account_name, instagram_id = excluded.instagram_id,
    instagram_username = excluded.instagram_username, expires_at = excluded.expires_at,
    last_error = NULL, connected_by = excluded.connected_by, connected_at = excluded.connected_at,
    updated_at = excluded.updated_at
RETURNING platform, status, token, account_id, account_name, instagram_id, instagram_username, expires_at, last_error, connected_by, connected_at, updated_at
`

type SaveConnectionParams struct {
	Platform          string
	Status            string
	Token             []byte
	AccountID         pgtype.Text
	AccountName       pgtype.Text
	InstagramID       pgtype.Text
	InstagramUsername pgtype.Text
	ExpiresAt         sql.NullTime
	ConnectedBy       pgtype.UUID
	Now               time.Time
}

// SaveConnection replaces a platform's connection whole.
func (q *Queries) SaveConnection(ctx context.Context, arg SaveConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, saveConnection,
		arg.Platform,
		arg.Status,
		arg.Token,
		arg.AccountID,
		arg.AccountName,
		arg.InstagramID,
		arg.InstagramUsername,
		arg.ExpiresAt,
		arg.ConnectedBy,
		arg.Now,
	)
	var i Connection
	err := row.Scan(
		&i.Platform,
		&i.Status,
		&i.Token,
		&i.AccountID,
		&i.AccountName,
		&i.InstagramID,
		&i.InstagramUsername,
		&i.ExpiresAt,
		&i.LastError,
		&i.ConnectedBy,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConnectionError = `-- name: SetConnectionError :exec
UPDATE connections SET last_error = $1, updated_at = $2 WHERE platform = $3
`

type SetConnectionErrorParams struct {
	LastError pgtype.Text
	Now       time.Time
	Platform  string
}

func (q *Queries) SetConnectionError(ctx context.Context, arg SetConnectionErrorParams) error {
	_, err := q.db.Exec(ctx, setConnectionError, arg.LastError, arg.Now, arg.Platform)
	return err
}
