// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_enquiries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRetainedContactEnquiries = `-- name: DeleteRetainedContactEnquiries :execrows
DELETE FROM contact_enquiries
WHERE id IN (
    SELECT e.id FROM contact_enquiries e WHERE e.created_at < $1 LIMIT $2
)
`

type DeleteRetainedContactEnquiriesParams struct {
	Before  time.Time
	MaxRows int32
}

// DeleteRetainedContactEnquiries deletes up to @max_rows enquiries created
// before @before, whatever their status; their communications go with them.
func (q *Queries) DeleteRetainedContactEnquiries(ctx context.Context, arg DeleteRetainedContactEnquiriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetainedContactEnquiries, arg.Before, arg.MaxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContactEnquiry = `-- name: GetContactEnquiry :one
SELECT e.id, e.reference, e.name, e.email, e.organisation, e.subject, e.enquiry_type, e.service_id, e.message, e.locale, e.privacy_ack_at, e.status, e.handled_at, e.handled_by, e.created_at, s.slug AS service_slug, s.name AS service_name
FROM contact_enquiries e
LEFT JOIN services s ON s.id = e.service_id
WHERE e.id = $1
`

type GetContactEnquiryRow struct {
	ID           pgtype.UUID
	Reference    string
	Name         string
	Email        string
	Organisation pgtype.Text
	Subject      pgtype.Text
	EnquiryType  string
	ServiceID    pgtype.UUID
	Message      string
	Locale       string
	PrivacyAckAt time.Time
	Status       string
	HandledAt    sql.NullTime
	HandledBy    pgtype.UUID
	CreatedAt    time.Time
	ServiceSlug  pgtype.Text
	ServiceName  json.RawMessage
}

func (q *Queries) GetContactEnquiry(ctx context.Context, id pgtype.UUID) (GetContactEnquiryRow, error) {
	row := q.db.QueryRow(ctx, getContactEnquiry, id)
	var i GetContactEnquiryRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Name,
		&i.Email,
		&i.Organisation,
		&i.Subject,
		&i.EnquiryType,
		&i.ServiceID,
		&i.Message,
		&i.Locale,
		&i.PrivacyAckAt,
		&i.Status,
		&i.HandledAt,
		&i.HandledBy,
		&i.CreatedAt,
		&i.ServiceSlug,
		&i.ServiceName,
	)
	return i, err
}

const insertContactEnquiry = `-- name: InsertContactEnquiry :one
INSERT INTO contact_enquiries (
    reference, name, email, organisation, subject, enquiry_type, service_id, message, locale,
    privacy_ack_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $10
)
ON CONFLICT (reference) DO NOTHING
RETURNING id, reference, name, email, organisation, subject, enquiry_type, service_id, message, locale, privacy_ack_at, status, handled_at, handled_by, created_at
`

type InsertContactEnquiryParams struct {
	Reference    string
	Name         string
	Email        string
	Organisation pgtype.Text
	Subject      pgtype.Text
	EnquiryType  string
	ServiceID    pgtype.UUID
	Message      string
	Locale       string
	PrivacyAckAt time.Time
}

// InsertContactEnquiry does nothing on a reference collision, so the caller
// can retry with a new reference inside the same transaction.
func (q *Queries) InsertContactEnquiry(ctx context.Context, arg InsertContactEnquiryParams) (ContactEnquiry, error) {
	row := q.db.QueryRow(ctx, insertContactEnquiry,
		arg.Reference,
		arg.Name,
		arg.Email,
		arg.Organisation,
		arg.Subject,
		arg.EnquiryType,
		arg.ServiceID,
		arg.Message,
		arg.Locale,
		arg.PrivacyAckAt,
	)
	var i ContactEnquiry
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Name,
		&i.Email,
		&i.Organisation,
		&i.Subject,
		&i.EnquiryType,
		&i.ServiceID,
		&i.Message,
		&i.Locale,
		&i.PrivacyAckAt,
		&i.Status,
		&i.HandledAt,
		&i.HandledBy,
		&i.CreatedAt,
	)
	return i, err
}

const listContactEnquiries = `-- name: ListContactEnquiries :many
SELECT e.id, e.reference, e.name, e.email, e.organisation, e.subject, e.enquiry_type, e.service_id, e.message, e.locale, e.privacy_ack_at, e.status, e.handled_at, e.handled_by, e.created_at, s.slug AS service_slug, s.name AS service_name
FROM contact_enquiries e
LEFT JOIN services s ON s.id = e.service_id
WHERE ($1::text IS NULL OR e.status = $1)
  AND ($2::text IS NULL OR e.reference ILIKE $2
       OR e.name ILIKE $2 OR e.email ILIKE $2
       OR e.organisation ILIKE $2 OR e.subject ILIKE $2)
  AND ($3::timestamptz IS NULL
       OR (e.created_at, e.id) < ($3, $4::uuid))
ORDER BY e.created_at DESC, e.id DESC
LIMIT $5
`

type ListContactEnquiriesParams struct {
	Status  pgtype.Text
	Search  pgtype.Text
	AfterAt sql.NullTime
	AfterID pgtype.UUID
	MaxRows int32
}

type ListContactEnquiriesRow struct {
	ID           pgtype.UUID
	Reference    string
	Name         string
	Email        string
	Organisation pgtype.Text
	Subject      pgtype.Text
	EnquiryType  string
	ServiceID    pgtype.UUID
	Message      string
	Locale       string
	PrivacyAckAt time.Time
	Status       string
	HandledAt    sql.NullTime
	HandledBy    pgtype.UUID
	CreatedAt    time.Time
	ServiceSlug  pgtype.Text
	ServiceName  json.RawMessage
}

// ListContactEnquiries is newest first; the page continues after
// (@after_at, @after_id).
func (q *Queries) ListContactEnquiries(ctx context.Context, arg ListContactEnquiriesParams) ([]ListContactEnquiriesRow, error) {
	rows, err := q.db.Query(ctx, listContactEnquiries,
		arg.Status,
		arg.Search,
		arg.AfterAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactEnquiriesRow{}
	for rows.Next() {
		var i ListContactEnquiriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Name,
			&i.Email,
			&i.Organisation,
			&i.Subject,
			&i.EnquiryType,
			&i.ServiceID,
			&i.Message,
			&i.Locale,
			&i.PrivacyAckAt,
			&i.Status,
			&i.HandledAt,
			&i.HandledBy,
			&i.CreatedAt,
			&i.ServiceSlug,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContactEnquiryHandled = `-- name: MarkContactEnquiryHandled :execrows
UPDATE contact_enquiries
SET status = 'handled', handled_at = $1::timestamptz, handled_by = $2
WHERE id = $3 AND status = 'new'
`

type MarkContactEnquiryHandledParams struct {
	Now       time.Time
	HandledBy pgtype.UUID
	ID        pgtype.UUID
}

// MarkContactEnquiryHandled leaves a handled enquiry as it is.
func (q *Queries) MarkContactEnquiryHandled(ctx context.Context, arg MarkContactEnquiryHandledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markContactEnquiryHandled, arg.Now, arg.HandledBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
