// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardCounts = `-- name: DashboardCounts :one
SELECT count(*) FILTER (WHERE status = 'pending') AS pending,
       count(*) FILTER (WHERE status = 'confirmed' AND starts_at >= $1::timestamptz) AS confirmed,
       count(*) FILTER (WHERE starts_at >= $2::timestamptz AND starts_at < $3::timestamptz) AS today,
       count(*) FILTER (WHERE starts_at >= $4::timestamptz AND starts_at < $5::timestamptz) AS this_week
FROM appointments
WHERE status IN ('pending', 'confirmed')
`

type DashboardCountsParams struct {
	Now       time.Time
	DayStart  time.Time
	DayEnd    time.Time
	WeekStart time.Time
	WeekEnd   time.Time
}

type DashboardCountsRow struct {
	Pending   int64
	Confirmed int64
	Today     int64
	ThisWeek  int64
}

func (q *Queries) DashboardCounts(ctx context.Context, arg DashboardCountsParams) (DashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardCounts,
		arg.Now,
		arg.DayStart,
		arg.DayEnd,
		arg.WeekStart,
		arg.WeekEnd,
	)
	var i DashboardCountsRow
	err := row.Scan(
		&i.Pending,
		&i.Confirmed,
		&i.Today,
		&i.ThisWeek,
	)
	return i, err
}

const listAttention = `-- name: ListAttention :many
WITH items AS (
    SELECT 1 AS rank, 'pending_request' AS kind, a.id, coalesce(a.hold_expires_at, a.starts_at) AS sort_at,
           ''::text AS communication_kind
    FROM appointments a
    WHERE a.status = 'pending'
    UNION ALL
    SELECT 2, 'hold_expiring', a.id, a.hold_expires_at, ''
    FROM appointments a
    WHERE a.status = 'pending' AND a.hold_expires_at <= $1::timestamptz
    UNION ALL
    SELECT DISTINCT 3, 'failed_communication', a.id, a.starts_at, f.kind
    FROM communications f
    JOIN appointments a ON a.id = f.appointment_id
    WHERE f.status = 'failed'
      AND NOT EXISTS (
          SELECT 1 FROM communications s
          WHERE s.appointment_id = f.appointment_id AND s.kind = f.kind AND s.status = 'sent'
            AND s.created_at > f.created_at)
    UNION ALL
    SELECT 4, 'reschedule_requested', a.id, a.starts_at, ''
    FROM appointments a
    WHERE a.status IN ('pending', 'confirmed')
      AND EXISTS (
          SELECT 1 FROM appointment_events r
          WHERE r.appointment_id = a.id AND r.kind = 'reschedule_requested'
            AND r.id > coalesce((
                SELECT max(e.id) FROM appointment_events e
                WHERE e.appointment_id = a.id AND (e.kind = 'rescheduled' OR e.to_status IS NOT NULL)
            ), 0))
    UNION ALL
    SELECT 5, 'completion_due', a.id, a.starts_at, ''
    FROM appointments a
    WHERE a.status = 'confirmed' AND a.ends_at < $2::timestamptz
    UNION ALL
    SELECT 6, 'block_conflict', a.id, a.starts_at, ''
    FROM appointments a
    WHERE a.status IN ('pending', 'confirmed')
      AND EXISTS (SELECT 1 FROM availability_blocks b WHERE b.period && a.busy_range)
)
SELECT i.kind::text AS kind, i.communication_kind::text AS communication_kind,
       a.id, a.reference, a.starts_at, a.hold_expires_at
FROM items i
JOIN appointments a ON a.id = i.id
ORDER BY i.rank, i.sort_at, a.id
`

type ListAttentionParams struct {
	HoldHorizon time.Time
	Now         time.Time
}

type ListAttentionRow struct {
	Kind              string
	CommunicationKind string
	ID                pgtype.UUID
	Reference         string
	StartsAt          time.Time
	HoldExpiresAt     sql.NullTime
}

// ListAttention returns every attention item in dashboard order; rank orders the kinds and the Go side
// writes each item's detail. A failed message counts until a later message of its kind is sent.
func (q *Queries) ListAttention(ctx context.Context, arg ListAttentionParams) ([]ListAttentionRow, error) {
	rows, err := q.db.Query(ctx, listAttention, arg.HoldHorizon, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttentionRow{}
	for rows.Next() {
		var i ListAttentionRow
		if err := rows.Scan(
			&i.Kind,
			&i.CommunicationKind,
			&i.ID,
			&i.Reference,
			&i.StartsAt,
			&i.HoldExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
