// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE ctid IN (
    SELECT k.ctid FROM idempotency_keys k WHERE k.created_at < $1 LIMIT $2
)
`

type DeleteExpiredIdempotencyKeysParams struct {
	Before  time.Time
	MaxRows int32
}

// DeleteExpiredIdempotencyKeys deletes up to @max_rows keys created before
// @before, so one run never holds a long lock.
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, arg DeleteExpiredIdempotencyKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, arg.Before, arg.MaxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishIdempotencyKey = `-- name: FinishIdempotencyKey :exec
UPDATE idempotency_keys
SET resource_id = $1, response_status = $2, response_body = $3
WHERE scope = $4 AND key = $5
`

type FinishIdempotencyKeyParams struct {
	ResourceID     pgtype.UUID
	ResponseStatus pgtype.Int2
	ResponseBody   []byte
	Scope          string
	Key            string
}

func (q *Queries) FinishIdempotencyKey(ctx context.Context, arg FinishIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, finishIdempotencyKey,
		arg.ResourceID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Scope,
		arg.Key,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT scope, key, request_hash, resource_id, response_status, response_body, created_at FROM idempotency_keys WHERE scope = $1 AND key = $2 FOR UPDATE
`

type GetIdempotencyKeyParams struct {
	Scope string
	Key   string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.ResourceID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :execrows
INSERT INTO idempotency_keys (scope, key, request_hash, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (scope, key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	Scope       string
	Key         string
	RequestHash []byte
	CreatedAt   time.Time
}

// InsertIdempotencyKey waits for a transaction holding the same key, then
// inserts nothing if that transaction committed.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
