// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (width, height, widths, byte_size, alt, credit, uploaded_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, width, height, widths, byte_size, alt, credit, uploaded_by, version, created_at, updated_at
`

type CreateMediaParams struct {
	Width      int32
	Height     int32
	Widths     []int32
	ByteSize   int64
	Alt        json.RawMessage
	Credit     pgtype.Text
	UploadedBy pgtype.UUID
	Now        time.Time
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Width,
		arg.Height,
		arg.Widths,
		arg.ByteSize,
		arg.Alt,
		arg.Credit,
		arg.UploadedBy,
		arg.Now,
	)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.Widths,
		&i.ByteSize,
		&i.Alt,
		&i.Credit,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnusedMedia = `-- name: DeleteUnusedMedia :one
DELETE FROM media
WHERE id = $1
  AND NOT EXISTS (SELECT 1 FROM post_versions v
                  WHERE v.cover_image_id = $1 OR $1 = ANY (v.image_ids))
  AND NOT EXISTS (SELECT 1 FROM published_articles a WHERE a.cover_image_id = $1)
RETURNING id, width, height, widths, byte_size, alt, credit, uploaded_by, version, created_at, updated_at
`

// DeleteUnusedMedia deletes an item no post version or published article
// shows, whatever the post's status; no row back means it is gone or in use.
func (q *Queries) DeleteUnusedMedia(ctx context.Context, id pgtype.UUID) (Media, error) {
	row := q.db.QueryRow(ctx, deleteUnusedMedia, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.Widths,
		&i.ByteSize,
		&i.Alt,
		&i.Credit,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existingMedia = `-- name: ExistingMedia :many
SELECT id FROM media WHERE id = ANY ($1::uuid[])
`

func (q *Queries) ExistingMedia(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, existingMedia, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMedia = `-- name: GetMedia :one
SELECT id, width, height, widths, byte_size, alt, credit, uploaded_by, version, created_at, updated_at FROM media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id pgtype.UUID) (Media, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.Widths,
		&i.ByteSize,
		&i.Alt,
		&i.Credit,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, width, height, widths, byte_size, alt, credit, uploaded_by, version, created_at, updated_at FROM media
WHERE ($1::text IS NULL
       OR alt->>'en' ILIKE $1 OR alt->>'my' ILIKE $1
       OR credit ILIKE $1)
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMediaParams struct {
	Search  pgtype.Text
	AfterAt sql.NullTime
	AfterID pgtype.UUID
	MaxRows int32
}

// ListMedia is newest first; the page continues after (@after_at, @after_id).
func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Media, error) {
	rows, err := q.db.Query(ctx, listMedia,
		arg.Search,
		arg.AfterAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Media{}
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.Width,
			&i.Height,
			&i.Widths,
			&i.ByteSize,
			&i.Alt,
			&i.Credit,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media
SET alt = $1, credit = $2, version = version + 1, updated_at = $3
WHERE id = $4 AND version = $5
RETURNING id, width, height, widths, byte_size, alt, credit, uploaded_by, version, created_at, updated_at
`

type UpdateMediaParams struct {
	Alt     json.RawMessage
	Credit  pgtype.Text
	Now     time.Time
	ID      pgtype.UUID
	Version int32
}

// UpdateMedia changes the description as of @version; no row back means the
// item is gone or changed since it was read.
func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Media, error) {
	row := q.db.QueryRow(ctx, updateMedia,
		arg.Alt,
		arg.Credit,
		arg.Now,
		arg.ID,
		arg.Version,
	)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.Widths,
		&i.ByteSize,
		&i.Alt,
		&i.Credit,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
