// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID                  pgtype.UUID
	Reference           string
	PractitionerID      pgtype.UUID
	ServiceID           pgtype.UUID
	Status              string
	StartsAt            time.Time
	EndsAt              time.Time
	DurationMinutes     int32
	BusyRange           pgtype.Range[pgtype.Timestamptz]
	Timezone            string
	Format              string
	Locale              string
	Source              string
	VisitorName         string
	VisitorEmail        string
	VisitorPhone        pgtype.Text
	VisitorNote         pgtype.Text
	PrivacyAckAt        sql.NullTime
	PolicyAckAt         sql.NullTime
	HoldExpiresAt       sql.NullTime
	ManagementTokenSeed []byte
	ManagementTokenHash []byte
	MeetingLink         pgtype.Text
	AdminNote           pgtype.Text
	LateCancellation    bool
	StatusChangedAt     time.Time
	CreatedBy           pgtype.UUID
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AppointmentEvent struct {
	ID            int64
	AppointmentID pgtype.UUID
	Kind          string
	FromStatus    pgtype.Text
	ToStatus      pgtype.Text
	PreviousRange pgtype.Range[pgtype.Timestamptz]
	NewRange      pgtype.Range[pgtype.Timestamptz]
	Actor         string
	ActorUserID   pgtype.UUID
	Detail        []byte
	CreatedAt     time.Time
}

type AvailabilityBlock struct {
	ID        pgtype.UUID
	Period    pgtype.Range[pgtype.Timestamptz]
	AllDay    bool
	Reason    pgtype.Text
	CreatedBy pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AvailabilityOverride struct {
	ID        pgtype.UUID
	OnDate    pgtype.Date
	Kind      string
	Period    pgtype.Range[pgtype.Timestamptz]
	Note      pgtype.Text
	CreatedBy pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AvailabilityRule struct {
	ID        pgtype.UUID
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Communication struct {
	ID                pgtype.UUID
	AppointmentID     pgtype.UUID
	ContactEnquiryID  pgtype.UUID
	Kind              string
	Audience          string
	Channel           string
	Recipient         pgtype.Text
	Locale            string
	Status            string
	ScheduledFor      time.Time
	SentAt            sql.NullTime
	ProviderMessageID pgtype.Text
	Error             pgtype.Text
	Attempts          int32
	ResendOf          pgtype.UUID
	CreatedBy         pgtype.UUID
	Note              pgtype.Text
	CreatedAt         time.Time
	Message           pgtype.Text
}

type ContactEnquiry struct {
	ID           pgtype.UUID
	Reference    string
	Name         string
	Email        string
	Organisation pgtype.Text
	Subject      pgtype.Text
	EnquiryType  string
	ServiceID    pgtype.UUID
	Message      string
	Locale       string
	PrivacyAckAt time.Time
	Status       string
	HandledAt    sql.NullTime
	HandledBy    pgtype.UUID
	CreatedAt    time.Time
}

type IdempotencyKey struct {
	Scope          string
	Key            string
	RequestHash    []byte
	ResourceID     pgtype.UUID
	ResponseStatus pgtype.Int2
	ResponseBody   []byte
	CreatedAt      time.Time
}

type Post struct {
	ID                 pgtype.UUID
	Title              string
	Kind               string
	Status             string
	ScheduledAt        sql.NullTime
	ConsentConfirmedAt sql.NullTime
	ConsentConfirmedBy pgtype.UUID
	ConsentNote        pgtype.Text
	ReviewNote         pgtype.Text
	AuthorID           pgtype.UUID
	ApprovedAt         sql.NullTime
	ApprovedBy         pgtype.UUID
	PublishedAt        sql.NullTime
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type PostPublication struct {
	PostID      pgtype.UUID
	Channel     string
	Status      string
	ExternalID  pgtype.Text
	Permalink   pgtype.Text
	Error       pgtype.Text
	Attempts    int32
	PublishedAt sql.NullTime
	UpdatedAt   time.Time
}

type PostVersion struct {
	PostID         pgtype.UUID
	Channel        string
	Enabled        bool
	Slug           pgtype.Text
	Title          json.RawMessage
	Excerpt        json.RawMessage
	Body           json.RawMessage
	CoverImageID   pgtype.UUID
	SeoTitle       json.RawMessage
	SeoDescription json.RawMessage
	Text           pgtype.Text
	LinkUrl        pgtype.Text
	ImageIds       []pgtype.UUID
	UpdatedAt      time.Time
}

type Service struct {
	ID                  pgtype.UUID
	Slug                string
	Name                json.RawMessage
	Description         json.RawMessage
	BookingAction       string
	State               string
	DurationMinutes     pgtype.Int4
	BufferBeforeMinutes int32
	BufferAfterMinutes  int32
	Formats             []string
	FeeText             json.RawMessage
	PreparationText     json.RawMessage
	SortOrder           int32
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	LastSeenAt time.Time
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedBy pgtype.UUID
	UpdatedAt time.Time
}

type User struct {
	ID             pgtype.UUID
	Email          string
	DisplayName    string
	PasswordHash   string
	Roles          []string
	IsPractitioner bool
	TotpSecretEnc  []byte
	TotpLastStep   pgtype.Int8
	LastSignInAt   sql.NullTime
	DisabledAt     sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type VideoRoom struct {
	ID            pgtype.UUID
	AppointmentID pgtype.UUID
	JoinTokenSeed []byte
	JoinTokenHash []byte
	OpensAt       time.Time
	ClosesAt      time.Time
	State         string
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	EndedReason   pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
