// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPostPublication = `-- name: ClaimPostPublication :one
UPDATE post_publications pub
SET status = 'publishing', attempts = pub.attempts + 1, updated_at = $1
FROM posts p
WHERE pub.post_id = $2 AND pub.channel = $3 AND p.id = pub.post_id
  AND p.status = 'publishing' AND pub.channel <> 'website'
  AND (pub.status = 'pending' OR (pub.status = 'publishing' AND pub.updated_at < $4))
RETURNING pub.post_id, pub.channel, pub.status, pub.external_id, pub.permalink, pub.error, pub.attempts, pub.published_at, pub.updated_at
`

type ClaimPostPublicationParams struct {
	Now         time.Time
	PostID      pgtype.UUID
	Channel     string
	StuckBefore time.Time
}

// ClaimPostPublication takes a social channel for the publishing worker:
// one that is pending, or stuck publishing since before @stuck_before, of a
// post still publishing. No row back means there is nothing to do.
func (q *Queries) ClaimPostPublication(ctx context.Context, arg ClaimPostPublicationParams) (PostPublication, error) {
	row := q.db.QueryRow(ctx, claimPostPublication,
		arg.Now,
		arg.PostID,
		arg.Channel,
		arg.StuckBefore,
	)
	var i PostPublication
	err := row.Scan(
		&i.PostID,
		&i.Channel,
		&i.Status,
		&i.ExternalID,
		&i.Permalink,
		&i.Error,
		&i.Attempts,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, kind, status, consent_confirmed_at, consent_confirmed_by, consent_note,
                   author_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $8)
RETURNING id, title, kind, status, scheduled_at, consent_confirmed_at, consent_confirmed_by, consent_note, review_note, author_id, approved_at, approved_by, published_at, version, created_at, updated_at
`

type CreatePostParams struct {
	Title              string
	Kind               string
	Status             string
	ConsentConfirmedAt sql.NullTime
	ConsentConfirmedBy pgtype.UUID
	ConsentNote        pgtype.Text
	AuthorID           pgtype.UUID
	Now                time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Kind,
		arg.Status,
		arg.ConsentConfirmedAt,
		arg.ConsentConfirmedBy,
		arg.ConsentNote,
		arg.AuthorID,
		arg.Now,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.ScheduledAt,
		&i.ConsentConfirmedAt,
		&i.ConsentConfirmedBy,
		&i.ConsentNote,
		&i.ReviewNote,
		&i.AuthorID,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts WHERE id = $1 AND status IN ('idea', 'draft')
`

// DeletePost deletes only ideas and drafts; anything further is archived.
func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishPostPublication = `-- name: FinishPostPublication :one
UPDATE post_publications
SET status = $1, external_id = $2, permalink = $3,
    error = $4, published_at = $5, updated_at = $6
WHERE post_id = $7 AND channel = $8 AND status = 'publishing'
RETURNING post_id, channel, status, external_id, permalink, error, attempts, published_at, updated_at
`

type FinishPostPublicationParams struct {
	Status      string
	ExternalID  pgtype.Text
	Permalink   pgtype.Text
	Error       pgtype.Text
	PublishedAt sql.NullTime
	Now         time.Time
	PostID      pgtype.UUID
	Channel     string
}

// FinishPostPublication records how the worker's attempt went.
func (q *Queries) FinishPostPublication(ctx context.Context, arg FinishPostPublicationParams) (PostPublication, error) {
	row := q.db.QueryRow(ctx, finishPostPublication,
		arg.Status,
		arg.ExternalID,
		arg.Permalink,
		arg.Error,
		arg.PublishedAt,
		arg.Now,
		arg.PostID,
		arg.Channel,
	)
	var i PostPublication
	err := row.Scan(
		&i.PostID,
		&i.Channel,
		&i.Status,
		&i.ExternalID,
		&i.Permalink,
		&i.Error,
		&i.Attempts,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, title, kind, status, scheduled_at, consent_confirmed_at, consent_confirmed_by, consent_note, review_note, author_id, approved_at, approved_by, published_at, version, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.ScheduledAt,
		&i.ConsentConfirmedAt,
		&i.ConsentConfirmedBy,
		&i.ConsentNote,
		&i.ReviewNote,
		&i.AuthorID,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicArticle = `-- name: GetPublicArticle :one
SELECT v.slug, p.kind, v.title, v.excerpt, v.body, v.seo_title, v.seo_description, pub.published_at,
       m.id AS cover_id, m.width AS cover_width, m.height AS cover_height,
       m.widths AS cover_widths, m.alt AS cover_alt
FROM post_versions v
JOIN posts p ON p.id = v.post_id
JOIN post_publications pub ON pub.post_id = v.post_id AND pub.channel = 'website'
LEFT JOIN media m ON m.id = v.cover_image_id
WHERE v.channel = 'website' AND v.slug = $1 AND v.enabled
  AND pub.status = 'published' AND p.status IN ('publishing', 'published')
`

type GetPublicArticleRow struct {
	Slug           pgtype.Text
	Kind           string
	Title          json.RawMessage
	Excerpt        json.RawMessage
	Body           json.RawMessage
	SeoTitle       json.RawMessage
	SeoDescription json.RawMessage
	PublishedAt    sql.NullTime
	CoverID        pgtype.UUID
	CoverWidth     pgtype.Int4
	CoverHeight    pgtype.Int4
	CoverWidths    []int32
	CoverAlt       json.RawMessage
}

func (q *Queries) GetPublicArticle(ctx context.Context, slug pgtype.Text) (GetPublicArticleRow, error) {
	row := q.db.QueryRow(ctx, getPublicArticle, slug)
	var i GetPublicArticleRow
	err := row.Scan(
		&i.Slug,
		&i.Kind,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.PublishedAt,
		&i.CoverID,
		&i.CoverWidth,
		&i.CoverHeight,
		&i.CoverWidths,
		&i.CoverAlt,
	)
	return i, err
}

const listDueScheduledPosts = `-- name: ListDueScheduledPosts :many
SELECT id, scheduled_at FROM posts
WHERE status = 'scheduled' AND scheduled_at < $1::timestamptz
ORDER BY scheduled_at
LIMIT $2
`

type ListDueScheduledPostsParams struct {
	Before  time.Time
	MaxRows int32
}

type ListDueScheduledPostsRow struct {
	ID          pgtype.UUID
	ScheduledAt sql.NullTime
}

func (q *Queries) ListDueScheduledPosts(ctx context.Context, arg ListDueScheduledPostsParams) ([]ListDueScheduledPostsRow, error) {
	rows, err := q.db.Query(ctx, listDueScheduledPosts, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueScheduledPostsRow{}
	for rows.Next() {
		var i ListDueScheduledPostsRow
		if err := rows.Scan(&i.ID, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostPublications = `-- name: ListPostPublications :many
SELECT post_id, channel, status, external_id, permalink, error, attempts, published_at, updated_at FROM post_publications WHERE post_id = $1 ORDER BY channel
`

func (q *Queries) ListPostPublications(ctx context.Context, postID pgtype.UUID) ([]PostPublication, error) {
	rows, err := q.db.Query(ctx, listPostPublications, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPublication{}
	for rows.Next() {
		var i PostPublication
		if err := rows.Scan(
			&i.PostID,
			&i.Channel,
			&i.Status,
			&i.ExternalID,
			&i.Permalink,
			&i.Error,
			&i.Attempts,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostVersions = `-- name: ListPostVersions :many
SELECT post_id, channel, enabled, slug, title, excerpt, body, cover_image_id, seo_title, seo_description, text, link_url, image_ids, updated_at FROM post_versions WHERE post_id = $1 ORDER BY channel
`

func (q *Queries) ListPostVersions(ctx context.Context, postID pgtype.UUID) ([]PostVersion, error) {
	rows, err := q.db.Query(ctx, listPostVersions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostVersion{}
	for rows.Next() {
		var i PostVersion
		if err := rows.Scan(
			&i.PostID,
			&i.Channel,
			&i.Enabled,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Body,
			&i.CoverImageID,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.Text,
			&i.LinkUrl,
			&i.ImageIds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.title, p.kind, p.status, p.scheduled_at, p.consent_confirmed_at, p.consent_confirmed_by, p.consent_note, p.review_note, p.author_id, p.approved_at, p.approved_by, p.published_at, p.version, p.created_at, p.updated_at,
       ARRAY(SELECT v.channel FROM post_versions v
             WHERE v.post_id = p.id AND v.enabled ORDER BY v.channel)::text[] AS channels
FROM posts p
WHERE ($1::text IS NULL OR p.status = $1)
  AND ($2::text IS NULL OR p.title ILIKE $2)
  AND ($3::timestamptz IS NULL
       OR (p.created_at, p.id) < ($3, $4::uuid))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $5
`

type ListPostsParams struct {
	Status  pgtype.Text
	Search  pgtype.Text
	AfterAt sql.NullTime
	AfterID pgtype.UUID
	MaxRows int32
}

type ListPostsRow struct {
	ID                 pgtype.UUID
	Title              string
	Kind               string
	Status             string
	ScheduledAt        sql.NullTime
	ConsentConfirmedAt sql.NullTime
	ConsentConfirmedBy pgtype.UUID
	ConsentNote        pgtype.Text
	ReviewNote         pgtype.Text
	AuthorID           pgtype.UUID
	ApprovedAt         sql.NullTime
	ApprovedBy         pgtype.UUID
	PublishedAt        sql.NullTime
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Channels           []string
}

// ListPosts is newest first; the page continues after (@after_at, @after_id).
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Status,
		arg.Search,
		arg.AfterAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Kind,
			&i.Status,
			&i.ScheduledAt,
			&i.ConsentConfirmedAt,
			&i.ConsentConfirmedBy,
			&i.ConsentNote,
			&i.ReviewNote,
			&i.AuthorID,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.PublishedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicArticles = `-- name: ListPublicArticles :many
SELECT v.slug, p.kind, v.title, v.excerpt, pub.published_at,
       m.id AS cover_id, m.width AS cover_width, m.height AS cover_height,
       m.widths AS cover_widths, m.alt AS cover_alt
FROM post_versions v
JOIN posts p ON p.id = v.post_id
JOIN post_publications pub ON pub.post_id = v.post_id AND pub.channel = 'website'
LEFT JOIN media m ON m.id = v.cover_image_id
WHERE v.channel = 'website' AND v.enabled AND pub.status = 'published'
  AND p.status IN ('publishing', 'published')
  AND ($1::text IS NULL OR p.kind = $1)
ORDER BY pub.published_at DESC, v.post_id DESC
LIMIT $2
`

type ListPublicArticlesParams struct {
	Kind    pgtype.Text
	MaxRows int32
}

type ListPublicArticlesRow struct {
	Slug        pgtype.Text
	Kind        string
	Title       json.RawMessage
	Excerpt     json.RawMessage
	PublishedAt sql.NullTime
	CoverID     pgtype.UUID
	CoverWidth  pgtype.Int4
	CoverHeight pgtype.Int4
	CoverWidths []int32
	CoverAlt    json.RawMessage
}

// ListPublicArticles selects the website versions that are live: enabled,
// published on the website, of a post that is publishing or published (not
// archived, nor back in review after an edit), with the cover image.
func (q *Queries) ListPublicArticles(ctx context.Context, arg ListPublicArticlesParams) ([]ListPublicArticlesRow, error) {
	rows, err := q.db.Query(ctx, listPublicArticles, arg.Kind, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicArticlesRow{}
	for rows.Next() {
		var i ListPublicArticlesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Kind,
			&i.Title,
			&i.Excerpt,
			&i.PublishedAt,
			&i.CoverID,
			&i.CoverWidth,
			&i.CoverHeight,
			&i.CoverWidths,
			&i.CoverAlt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckPostPublications = `-- name: ListStuckPostPublications :many
SELECT pub.post_id, pub.channel, pub.status, pub.external_id, pub.permalink, pub.error, pub.attempts, pub.published_at, pub.updated_at FROM post_publications pub
JOIN posts p ON p.id = pub.post_id
WHERE p.status = 'publishing' AND pub.channel <> 'website'
  AND pub.status IN ('pending', 'publishing') AND pub.updated_at < $1
ORDER BY pub.updated_at
LIMIT $2
`

type ListStuckPostPublicationsParams struct {
	Before  time.Time
	MaxRows int32
}

// ListStuckPostPublications finds social channels of publishing posts that
// have waited or run since before @before: their task was lost.
func (q *Queries) ListStuckPostPublications(ctx context.Context, arg ListStuckPostPublicationsParams) ([]PostPublication, error) {
	rows, err := q.db.Query(ctx, listStuckPostPublications, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPublication{}
	for rows.Next() {
		var i PostPublication
		if err := rows.Scan(
			&i.PostID,
			&i.Channel,
			&i.Status,
			&i.ExternalID,
			&i.Permalink,
			&i.Error,
			&i.Attempts,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPost = `-- name: LockPost :one
SELECT id, title, kind, status, scheduled_at, consent_confirmed_at, consent_confirmed_by, consent_note, review_note, author_id, approved_at, approved_by, published_at, version, created_at, updated_at FROM posts WHERE id = $1 FOR UPDATE
`

// LockPost reads a post for a change, holding it until the transaction ends.
func (q *Queries) LockPost(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, lockPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.ScheduledAt,
		&i.ConsentConfirmedAt,
		&i.ConsentConfirmedBy,
		&i.ConsentNote,
		&i.ReviewNote,
		&i.AuthorID,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPublicationManual = `-- name: MarkPublicationManual :one
UPDATE post_publications
SET status = 'manual', permalink = $1, error = NULL,
    published_at = coalesce(published_at, $2), updated_at = $2
WHERE post_id = $3 AND channel = $4 AND status IN ('pending', 'failed', 'manual')
RETURNING post_id, channel, status, external_id, permalink, error, attempts, published_at, updated_at
`

type MarkPublicationManualParams struct {
	Permalink pgtype.Text
	Now       time.Time
	PostID    pgtype.UUID
	Channel   string
}

// MarkPublicationManual records a channel Daw Mi posted herself; no row back
// means the channel was not waiting for her.
func (q *Queries) MarkPublicationManual(ctx context.Context, arg MarkPublicationManualParams) (PostPublication, error) {
	row := q.db.QueryRow(ctx, markPublicationManual,
		arg.Permalink,
		arg.Now,
		arg.PostID,
		arg.Channel,
	)
	var i PostPublication
	err := row.Scan(
		&i.PostID,
		&i.Channel,
		&i.Status,
		&i.ExternalID,
		&i.Permalink,
		&i.Error,
		&i.Attempts,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const openPostPublication = `-- name: OpenPostPublication :exec
INSERT INTO post_publications (post_id, channel, status, published_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (post_id, channel) DO UPDATE
SET status = excluded.status, error = NULL,
    published_at = coalesce(post_publications.published_at, excluded.published_at),
    updated_at = excluded.updated_at
WHERE post_publications.channel = 'website'
`

type OpenPostPublicationParams struct {
	PostID      pgtype.UUID
	Channel     string
	Status      string
	PublishedAt sql.NullTime
	Now         time.Time
}

// OpenPostPublication opens a channel's publication. Publishing a post again
// (after its website version was edited) republishes the website, keeping
// its first publication time, and leaves every social channel as it is.
func (q *Queries) OpenPostPublication(ctx context.Context, arg OpenPostPublicationParams) error {
	_, err := q.db.Exec(ctx, openPostPublication,
		arg.PostID,
		arg.Channel,
		arg.Status,
		arg.PublishedAt,
		arg.Now,
	)
	return err
}

const retryPostPublication = `-- name: RetryPostPublication :one
UPDATE post_publications
SET status = 'pending', error = NULL, attempts = 0, updated_at = $1
WHERE post_id = $2 AND channel = $3 AND status = 'failed'
RETURNING post_id, channel, status, external_id, permalink, error, attempts, published_at, updated_at
`

type RetryPostPublicationParams struct {
	Now     time.Time
	PostID  pgtype.UUID
	Channel string
}

// RetryPostPublication gives a failed channel a fresh set of attempts.
func (q *Queries) RetryPostPublication(ctx context.Context, arg RetryPostPublicationParams) (PostPublication, error) {
	row := q.db.QueryRow(ctx, retryPostPublication, arg.Now, arg.PostID, arg.Channel)
	var i PostPublication
	err := row.Scan(
		&i.PostID,
		&i.Channel,
		&i.Status,
		&i.ExternalID,
		&i.Permalink,
		&i.Error,
		&i.Attempts,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savePost = `-- name: SavePost :one
UPDATE posts
SET title = $1, kind = $2, status = $3, scheduled_at = $4,
    consent_confirmed_at = $5,
    consent_confirmed_by = $6, consent_note = $7,
    review_note = $8, approved_at = $9,
    approved_by = $10, published_at = $11,
    version = version + 1, updated_at = $12
WHERE id = $13
RETURNING id, title, kind, status, scheduled_at, consent_confirmed_at, consent_confirmed_by, consent_note, review_note, author_id, approved_at, approved_by, published_at, version, created_at, updated_at
`

type SavePostParams struct {
	Title              string
	Kind               string
	Status             string
	ScheduledAt        sql.NullTime
	ConsentConfirmedAt sql.NullTime
	ConsentConfirmedBy pgtype.UUID
	ConsentNote        pgtype.Text
	ReviewNote         pgtype.Text
	ApprovedAt         sql.NullTime
	ApprovedBy         pgtype.UUID
	PublishedAt        sql.NullTime
	Now                time.Time
	ID                 pgtype.UUID
}

// SavePost writes every field a change may touch; the caller holds the lock.
func (q *Queries) SavePost(ctx context.Context, arg SavePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, savePost,
		arg.Title,
		arg.Kind,
		arg.Status,
		arg.ScheduledAt,
		arg.ConsentConfirmedAt,
		arg.ConsentConfirmedBy,
		arg.ConsentNote,
		arg.ReviewNote,
		arg.ApprovedAt,
		arg.ApprovedBy,
		arg.PublishedAt,
		arg.Now,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.ScheduledAt,
		&i.ConsentConfirmedAt,
		&i.ConsentConfirmedBy,
		&i.ConsentNote,
		&i.ReviewNote,
		&i.AuthorID,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savePostVersion = `-- name: SavePostVersion :exec
INSERT INTO post_versions (post_id, channel, enabled, slug, title, excerpt, body, cover_image_id,
                           seo_title, seo_description, text, link_url, image_ids, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10,
        $11, $12, $13, $14)
ON CONFLICT (post_id, channel) DO UPDATE
SET enabled = excluded.enabled, slug = excluded.slug, title = excluded.title,
    excerpt = excluded.excerpt, body = excluded.body, cover_image_id = excluded.cover_image_id,
    seo_title = excluded.seo_title, seo_description = excluded.seo_description,
    text = excluded.text, link_url = excluded.link_url, image_ids = excluded.image_ids,
    updated_at = excluded.updated_at
`

type SavePostVersionParams struct {
	PostID         pgtype.UUID
	Channel        string
	Enabled        bool
	Slug           pgtype.Text
	Title          json.RawMessage
	Excerpt        json.RawMessage
	Body           json.RawMessage
	CoverImageID   pgtype.UUID
	SeoTitle       json.RawMessage
	SeoDescription json.RawMessage
	Text           pgtype.Text
	LinkUrl        pgtype.Text
	ImageIds       []pgtype.UUID
	Now            time.Time
}

func (q *Queries) SavePostVersion(ctx context.Context, arg SavePostVersionParams) error {
	_, err := q.db.Exec(ctx, savePostVersion,
		arg.PostID,
		arg.Channel,
		arg.Enabled,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.CoverImageID,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.Text,
		arg.LinkUrl,
		arg.ImageIds,
		arg.Now,
	)
	return err
}
