// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// CancelAppointmentByClient is a visitor's cancellation through the
	// management link; the caller has checked it with booking.CanTransition.
	CancelAppointmentByClient(ctx context.Context, arg CancelAppointmentByClientParams) (Appointment, error)
	// ClaimTOTPStep is the replay guard: a step is accepted once, and only if it
	// is later than the last one accepted, so two concurrent sign-ins with one
	// code cannot both succeed.
	ClaimTOTPStep(ctx context.Context, arg ClaimTOTPStepParams) (int64, error)
	// CloseOverdueVideoRooms ends every room still open past its window, for the
	// sweep that catches close-room tasks Redis lost.
	CloseOverdueVideoRooms(ctx context.Context, now time.Time) (int64, error)
	// CloseVideoRoomIfDue ends a room whose window has passed; a room moved
	// later, or already ended, is left alone.
	CloseVideoRoomIfDue(ctx context.Context, arg CloseVideoRoomIfDueParams) error
	CreateAvailabilityBlock(ctx context.Context, arg CreateAvailabilityBlockParams) (AvailabilityBlock, error)
	CreateAvailabilityOverride(ctx context.Context, arg CreateAvailabilityOverrideParams) (AvailabilityOverride, error)
	CreateAvailabilityRule(ctx context.Context, arg CreateAvailabilityRuleParams) (AvailabilityRule, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostPublication(ctx context.Context, arg CreatePostPublicationParams) error
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error)
	// CreateUser and ReplaceUserCredentials store the step of the code typed at
	// enrolment as already accepted, so that code can never also sign in.
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	DeleteAvailabilityBlock(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteAvailabilityOverride(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteAvailabilityRule(ctx context.Context, id pgtype.UUID) (int64, error)
	// DeleteExpiredIdempotencyKeys deletes up to @max_rows keys created before
	// @before, so one run never holds a long lock.
	DeleteExpiredIdempotencyKeys(ctx context.Context, arg DeleteExpiredIdempotencyKeysParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error)
	// DeletePost deletes only ideas and drafts; anything further is archived.
	DeletePost(ctx context.Context, id pgtype.UUID) (int64, error)
	// DeleteRetainedAppointments deletes up to @max_rows final appointments that
	// ended before @before; their events and communications go with them by
	// ON DELETE CASCADE. Pending and confirmed rows are never deleted.
	DeleteRetainedAppointments(ctx context.Context, arg DeleteRetainedAppointmentsParams) (int64, error)
	// DeleteRetainedContactEnquiries deletes up to @max_rows enquiries created
	// before @before, whatever their status; their communications go with them.
	DeleteRetainedContactEnquiries(ctx context.Context, arg DeleteRetainedContactEnquiriesParams) (int64, error)
	DeleteService(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	// EndVideoRoom ends an appointment's room for a reason; a room already
	// ended is left as it is, so of two racing ends exactly one writes.
	EndVideoRoom(ctx context.Context, arg EndVideoRoomParams) (VideoRoom, error)
	FinishIdempotencyKey(ctx context.Context, arg FinishIdempotencyKeyParams) error
	GetAppointmentDetail(ctx context.Context, id pgtype.UUID) (GetAppointmentDetailRow, error)
	GetAppointmentForMessage(ctx context.Context, id pgtype.UUID) (GetAppointmentForMessageRow, error)
	GetAppointmentStatus(ctx context.Context, id pgtype.UUID) (string, error)
	GetCommunication(ctx context.Context, id pgtype.UUID) (Communication, error)
	GetContactEnquiry(ctx context.Context, id pgtype.UUID) (GetContactEnquiryRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	// GetManagedAppointment looks a management link up by its token's hash,
	// never by a seed or an id.
	GetManagedAppointment(ctx context.Context, tokenHash []byte) (GetManagedAppointmentRow, error)
	GetPost(ctx context.Context, id pgtype.UUID) (Post, error)
	GetPractitionerID(ctx context.Context) (pgtype.UUID, error)
	GetPublicArticle(ctx context.Context, slug pgtype.Text) (GetPublicArticleRow, error)
	GetService(ctx context.Context, id pgtype.UUID) (Service, error)
	GetServiceBySlug(ctx context.Context, slug string) (Service, error)
	// GetSession returns the session a token hash names together with its user,
	// so authenticating a request is one query.
	GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error)
	GetUserForSignIn(ctx context.Context, email string) (GetUserForSignInRow, error)
	GetVideoRoom(ctx context.Context, id pgtype.UUID) (VideoRoom, error)
	GetVideoRoomByAppointment(ctx context.Context, appointmentID pgtype.UUID) (VideoRoom, error)
	// GetVideoSessionByTokenHash is a room with what its join page shows of the
	// appointment: times, status, locale and the service's public name.
	GetVideoSessionByTokenHash(ctx context.Context, joinTokenHash []byte) (GetVideoSessionByTokenHashRow, error)
	// InsertAppointment does nothing on a reference collision, so the caller can
	// retry with a new reference inside the same transaction. Every other
	// violation, appointments_no_overlap included, is an error.
	InsertAppointment(ctx context.Context, arg InsertAppointmentParams) (Appointment, error)
	InsertAppointmentEvent(ctx context.Context, arg InsertAppointmentEventParams) error
	InsertCommunication(ctx context.Context, arg InsertCommunicationParams) (Communication, error)
	// InsertContactEnquiry does nothing on a reference collision, so the caller
	// can retry with a new reference inside the same transaction.
	InsertContactEnquiry(ctx context.Context, arg InsertContactEnquiryParams) (ContactEnquiry, error)
	// InsertIdempotencyKey waits for a transaction holding the same key, then
	// inserts nothing if that transaction committed.
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error)
	InsertVideoRoom(ctx context.Context, arg InsertVideoRoomParams) (VideoRoom, error)
	// LatestRescheduleRequest is the detail of the visitor's newest request.
	LatestRescheduleRequest(ctx context.Context, appointmentID pgtype.UUID) ([]byte, error)
	// ListAppointmentCommunications is an appointment's messages in the order
	// they were written; rows of one transaction share created_at, so the time
	// each is due orders them, and the id keeps the order stable.
	ListAppointmentCommunications(ctx context.Context, appointmentID pgtype.UUID) ([]Communication, error)
	ListAppointmentEvents(ctx context.Context, appointmentID pgtype.UUID) ([]ListAppointmentEventsRow, error)
	// ListAppointments serves the admin list (booking.ListAppointments). sort_at
	// is the hold's end for the pending view and the start otherwise; the page
	// continues after (@after_at, @after_id) in the list's direction. @past
	// keeps rows that started before it or are final.
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error)
	ListAvailabilityBlocks(ctx context.Context, within pgtype.Range[pgtype.Timestamptz]) ([]AvailabilityBlock, error)
	ListAvailabilityOverrides(ctx context.Context, arg ListAvailabilityOverridesParams) ([]AvailabilityOverride, error)
	ListAvailabilityRules(ctx context.Context) ([]AvailabilityRule, error)
	// ListBusyPeriods is the time slot generation must keep free inside within:
	// every block and every pending or confirmed appointment's busy range. It
	// selects the periods alone, never a reason or anything about a visitor.
	// @except_id, when set, is an appointment being moved, whose own time is free
	// to it.
	ListBusyPeriods(ctx context.Context, arg ListBusyPeriodsParams) ([]pgtype.Range[pgtype.Timestamptz], error)
	// ListContactEnquiries is newest first; the page continues after
	// (@after_at, @after_id).
	ListContactEnquiries(ctx context.Context, arg ListContactEnquiriesParams) ([]ListContactEnquiriesRow, error)
	// ListDueCommunications serves comms:sweep through the partial index on
	// queued rows.
	ListDueCommunications(ctx context.Context, arg ListDueCommunicationsParams) ([]ListDueCommunicationsRow, error)
	// ListOverdueHolds serves booking:sweep-holds through the partial index on
	// pending holds.
	ListOverdueHolds(ctx context.Context, arg ListOverdueHoldsParams) ([]pgtype.UUID, error)
	ListOverlappingAppointments(ctx context.Context, period pgtype.Range[pgtype.Timestamptz]) ([]ListOverlappingAppointmentsRow, error)
	ListPostPublications(ctx context.Context, postID pgtype.UUID) ([]PostPublication, error)
	ListPostVersions(ctx context.Context, postID pgtype.UUID) ([]PostVersion, error)
	// ListPosts is newest first; the page continues after (@after_at, @after_id).
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	// ListPublicArticles selects the website versions that are live: published
	// on the website, of a post not archived.
	ListPublicArticles(ctx context.Context, arg ListPublicArticlesParams) ([]ListPublicArticlesRow, error)
	// ListPublicBookableServices selects only what a visitor may see.
	ListPublicBookableServices(ctx context.Context) ([]ListPublicBookableServicesRow, error)
	ListQueuedReminderIDs(ctx context.Context, appointmentID pgtype.UUID) ([]pgtype.UUID, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	// ListVideoRooms reads the rooms the hub holds sockets for.
	ListVideoRooms(ctx context.Context, ids []pgtype.UUID) ([]VideoRoom, error)
	LockAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error)
	LockAppointmentByTokenHash(ctx context.Context, tokenHash []byte) (Appointment, error)
	// LockCommunication skips a row another worker holds, so two workers given
	// the same task never both send it.
	LockCommunication(ctx context.Context, id pgtype.UUID) (Communication, error)
	// LockPost reads a post for a change, holding it until the transaction ends.
	LockPost(ctx context.Context, id pgtype.UUID) (Post, error)
	// LockSchedule takes the transaction-scoped lock that availability writes and
	// appointment creation share (docs/architecture.md, walkthrough 1, step 5),
	// keyed by the one practitioner.
	LockSchedule(ctx context.Context) error
	// MarkContactEnquiryHandled leaves a handled enquiry as it is.
	MarkContactEnquiryHandled(ctx context.Context, arg MarkContactEnquiryHandledParams) (int64, error)
	// MarkPublicationManual records a channel Daw Mi posted herself; no row back
	// means the channel was not waiting for her.
	MarkPublicationManual(ctx context.Context, arg MarkPublicationManualParams) (PostPublication, error)
	// MoveAppointment is a reschedule's one write (ADR-004): the new time is
	// taken in the same statement that releases the old, so an overlap refuses
	// the whole move. A pending hold never outlasts the new start.
	MoveAppointment(ctx context.Context, arg MoveAppointmentParams) (Appointment, error)
	// MoveVideoRoom follows a reschedule; an ended room stays as it is.
	MoveVideoRoom(ctx context.Context, arg MoveVideoRoomParams) ([]VideoRoom, error)
	Ping(ctx context.Context) (int32, error)
	// PreviousRangeOf is where the latest reschedule moved the appointment from.
	PreviousRangeOf(ctx context.Context, appointmentID pgtype.UUID) (pgtype.Range[pgtype.Timestamptz], error)
	// RecordSignIn succeeds only while the user is enabled and still has the
	// password hash sign-in verified. Its row lock orders it against a
	// concurrent create-user, whose session delete then sees this sign-in's
	// session, or whose new hash makes this update miss.
	RecordSignIn(ctx context.Context, arg RecordSignInParams) (int64, error)
	// ReplaceUserCredentials re-enrols an existing user. It never clears
	// is_practitioner: re-running create-user to reset Daw Mi's password without
	// --practitioner must not leave the practice without its practitioner.
	ReplaceUserCredentials(ctx context.Context, arg ReplaceUserCredentialsParams) (pgtype.UUID, error)
	// RescheduleQueuedReminders moves every queued reminder to its start less
	// @hours, the new reminder_hours.
	RescheduleQueuedReminders(ctx context.Context, hours int32) ([]RescheduleQueuedRemindersRow, error)
	// RescheduleRequestOpen reports a reschedule request newer than the last
	// reschedule or status change, which would have answered it.
	RescheduleRequestOpen(ctx context.Context, appointmentID pgtype.UUID) (bool, error)
	// SavePost writes every field a change may touch; the caller holds the lock.
	SavePost(ctx context.Context, arg SavePostParams) (Post, error)
	SavePostVersion(ctx context.Context, arg SavePostVersionParams) error
	SetAppointmentNote(ctx context.Context, arg SetAppointmentNoteParams) (Appointment, error)
	// SetAppointmentStatus is the one write of a status change; the caller has
	// checked it with booking.CanTransition. Only a pending or expired request
	// keeps its hold.
	SetAppointmentStatus(ctx context.Context, arg SetAppointmentStatusParams) (Appointment, error)
	SetCommunicationStatus(ctx context.Context, arg SetCommunicationStatusParams) (int64, error)
	// SetVideoRoomInSession marks a waiting room in session once both
	// participants have joined; started_at keeps the first time.
	SetVideoRoomInSession(ctx context.Context, arg SetVideoRoomInSessionParams) (int64, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAvailabilityBlock(ctx context.Context, arg UpdateAvailabilityBlockParams) (AvailabilityBlock, error)
	UpdateAvailabilityOverride(ctx context.Context, arg UpdateAvailabilityOverrideParams) (AvailabilityOverride, error)
	UpdateAvailabilityRule(ctx context.Context, arg UpdateAvailabilityRuleParams) (AvailabilityRule, error)
	// UpdateService writes the whole row only if nobody changed it since the
	// caller read version; no row back means they did.
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	// UpdateSettings writes every key of patch, a JSON object of key to value, in
	// one statement, so a patch lands whole or not at all. Keys with no row are
	// ignored; platform/settings only passes known keys.
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
}

var _ Querier = (*Queries)(nil)
