// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"
)

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT id, slug, name, description, booking_action, state, duration_minutes, buffer_before_minutes, buffer_after_minutes, formats, fee_text, preparation_text, sort_order, version, created_at, updated_at FROM services WHERE slug = $1
`

func (q *Queries) GetServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BookingAction,
		&i.State,
		&i.DurationMinutes,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.Formats,
		&i.FeeText,
		&i.PreparationText,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, slug, name, description, booking_action, state, duration_minutes, buffer_before_minutes, buffer_after_minutes, formats, fee_text, preparation_text, sort_order, version, created_at, updated_at FROM services ORDER BY sort_order, slug
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BookingAction,
			&i.State,
			&i.DurationMinutes,
			&i.BufferBeforeMinutes,
			&i.BufferAfterMinutes,
			&i.Formats,
			&i.FeeText,
			&i.PreparationText,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
