// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, last_seen_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	Now       time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.Now,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1 OR last_seen_at <= $2
`

type DeleteExpiredSessionsParams struct {
	Now        time.Time
	IdleBefore time.Time
}

func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, arg.Now, arg.IdleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.last_seen_at, s.expires_at,
       u.id AS user_id, u.email, u.display_name, u.roles, u.is_practitioner, u.disabled_at,
       (u.totp_secret_enc IS NOT NULL)::boolean AS two_step_enabled
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionRow struct {
	ID             pgtype.UUID
	LastSeenAt     time.Time
	ExpiresAt      time.Time
	UserID         pgtype.UUID
	Email          string
	DisplayName    string
	Roles          []string
	IsPractitioner bool
	DisabledAt     sql.NullTime
	TwoStepEnabled bool
}

// GetSession returns the session a token hash names together with its user,
// so authenticating a request is one query.
func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Roles,
		&i.IsPractitioner,
		&i.DisabledAt,
		&i.TwoStepEnabled,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1 WHERE id = $2
`

type TouchSessionParams struct {
	Now time.Time
	ID  pgtype.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Now, arg.ID)
	return err
}
