// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSettings = `-- name: ListSettings :many
SELECT key, value, updated_at FROM settings
`

type ListSettingsRow struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

func (q *Queries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings s
SET value = p.value, updated_by = $1, updated_at = $2
FROM jsonb_each($3::jsonb) AS p(key, value)
WHERE s.key = p.key
`

type UpdateSettingsParams struct {
	UpdatedBy pgtype.UUID
	Now       time.Time
	Patch     []byte
}

// UpdateSettings writes every key of patch, a JSON object of key to value, in
// one statement, so a patch lands whole or not at all. Keys with no row are
// ignored; platform/settings only passes known keys.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSettings, arg.UpdatedBy, arg.Now, arg.Patch)
	return err
}
