// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTOTPStep = `-- name: ClaimTOTPStep :execrows
UPDATE users
SET totp_last_step = $1::bigint
WHERE id = $2 AND (totp_last_step IS NULL OR totp_last_step < $1)
`

type ClaimTOTPStepParams struct {
	Step int64
	ID   pgtype.UUID
}

// ClaimTOTPStep is the replay guard: a step is accepted once, and only if it
// is later than the last one accepted, so two concurrent sign-ins with one
// code cannot both succeed.
func (q *Queries) ClaimTOTPStep(ctx context.Context, arg ClaimTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimTOTPStep, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, roles, is_practitioner, totp_secret_enc, totp_last_step)
VALUES ($1, $2, $3, $4, $5, $6, $7::bigint)
RETURNING id
`

type CreateUserParams struct {
	Email          string
	DisplayName    string
	PasswordHash   string
	Roles          []string
	IsPractitioner bool
	TotpSecretEnc  []byte
	TotpLastStep   pgtype.Int8
}

// CreateUser and ReplaceUserCredentials store the step of the code typed at
// enrolment as already accepted, so that code can never also sign in. A
// password-only user has a NULL secret and step.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Roles,
		arg.IsPractitioner,
		arg.TotpSecretEnc,
		arg.TotpLastStep,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPractitionerID = `-- name: GetPractitionerID :one
SELECT id FROM users WHERE is_practitioner
`

func (q *Queries) GetPractitionerID(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPractitionerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserForSignIn = `-- name: GetUserForSignIn :one
SELECT id, email, display_name, password_hash, roles, is_practitioner, totp_secret_enc
FROM users
WHERE email = $1
`

type GetUserForSignInRow struct {
	ID             pgtype.UUID
	Email          string
	DisplayName    string
	PasswordHash   string
	Roles          []string
	IsPractitioner bool
	TotpSecretEnc  []byte
}

func (q *Queries) GetUserForSignIn(ctx context.Context, email string) (GetUserForSignInRow, error) {
	row := q.db.QueryRow(ctx, getUserForSignIn, email)
	var i GetUserForSignInRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Roles,
		&i.IsPractitioner,
		&i.TotpSecretEnc,
	)
	return i, err
}

const recordSignIn = `-- name: RecordSignIn :execrows
UPDATE users
SET last_sign_in_at = $1::timestamptz
WHERE id = $2 AND disabled_at IS NULL AND password_hash = $3
`

type RecordSignInParams struct {
	Now          time.Time
	ID           pgtype.UUID
	PasswordHash string
}

// RecordSignIn succeeds only while the user is enabled and still has the
// password hash sign-in verified. Its row lock orders it against a
// concurrent create-user, whose session delete then sees this sign-in's
// session, or whose new hash makes this update miss.
func (q *Queries) RecordSignIn(ctx context.Context, arg RecordSignInParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordSignIn, arg.Now, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceUserCredentials = `-- name: ReplaceUserCredentials :one
UPDATE users
SET display_name = $1,
    password_hash = $2,
    roles = $3,
    is_practitioner = is_practitioner OR $4,
    totp_secret_enc = $5,
    totp_last_step = $6::bigint,
    updated_at = now()
WHERE email = $7
RETURNING id
`

type ReplaceUserCredentialsParams struct {
	DisplayName    string
	PasswordHash   string
	Roles          []string
	IsPractitioner bool
	TotpSecretEnc  []byte
	TotpLastStep   pgtype.Int8
	Email          string
}

// ReplaceUserCredentials re-enrols an existing user. It never clears
// is_practitioner: re-running create-user to reset Daw Mi's password without
// --practitioner must not leave the practice without its practitioner.
func (q *Queries) ReplaceUserCredentials(ctx context.Context, arg ReplaceUserCredentialsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, replaceUserCredentials,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Roles,
		arg.IsPractitioner,
		arg.TotpSecretEnc,
		arg.TotpLastStep,
		arg.Email,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
