// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTOTPStep = `-- name: ClaimTOTPStep :execrows
UPDATE users
SET totp_last_step = $1::bigint
WHERE id = $2 AND (totp_last_step IS NULL OR totp_last_step < $1)
`

type ClaimTOTPStepParams struct {
	Step int64
	ID   pgtype.UUID
}

// ClaimTOTPStep is the replay guard: a step is accepted once, and only if it
// is later than the last one accepted, so two concurrent sign-ins with one
// code cannot both succeed.
func (q *Queries) ClaimTOTPStep(ctx context.Context, arg ClaimTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimTOTPStep, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, roles, is_practitioner, totp_secret_enc, totp_last_step)
VALUES ($1, $2, $3, $4, $5, $6, $7::bigint)
RETURNING id
`

type CreateUserParams struct {
	Email          string
	DisplayName    string
	PasswordHash   string
	Roles          []string
	IsPractitioner bool
	TotpSecretEnc  []byte
	TotpLastStep   int64
}

// CreateUser and ReplaceUserCredentials store the step of the code typed at
// enrolment as already accepted, so that code can never also sign in.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Roles,
		arg.IsPractitioner,
		arg.TotpSecretEnc,
		arg.TotpLastStep,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserTOTPSecret = `-- name: GetUserTOTPSecret :one
SELECT totp_secret_enc FROM users WHERE id = $1
`

func (q *Queries) GetUserTOTPSecret(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserTOTPSecret, id)
	var totp_secret_enc []byte
	err := row.Scan(&totp_secret_enc)
	return totp_secret_enc, err
}

const replaceUserCredentials = `-- name: ReplaceUserCredentials :one
UPDATE users
SET display_name = $1,
    password_hash = $2,
    roles = $3,
    is_practitioner = is_practitioner OR $4,
    totp_secret_enc = $5,
    totp_last_step = $6::bigint,
    updated_at = now()
WHERE email = $7
RETURNING id
`

type ReplaceUserCredentialsParams struct {
	DisplayName    string
	PasswordHash   string
	Roles          []string
	IsPractitioner bool
	TotpSecretEnc  []byte
	TotpLastStep   int64
	Email          string
}

// ReplaceUserCredentials re-enrols an existing user. It never clears
// is_practitioner: re-running create-user to reset Daw Mi's password without
// --practitioner must not leave the practice without its practitioner.
func (q *Queries) ReplaceUserCredentials(ctx context.Context, arg ReplaceUserCredentialsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, replaceUserCredentials,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Roles,
		arg.IsPractitioner,
		arg.TotpSecretEnc,
		arg.TotpLastStep,
		arg.Email,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
